### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Grayzone90** [MrGreen-git/GisGmp#1]
Привет, никогда не работал на си шарп, можешь написать как мне запустить это проект допустим в rider`e или vs2019 в режиме отладки на допустим main методе в Program классе, хочу разобраться в коде для имплементации на другой язык, если си шарп не осилю, нужно для бизнесовой задачи =) . Или как этим пользоваться хотя бы пару примеров, ну хотелось это всё в отладку перевести, а там разберусь

На данный момент так

![Screenshot_12](https://user-images.githubusercontent.com/39431529/127056778-b049d41b-96f0-4852-8e5e-b770f2a60b7d.png)

**Comment by MrGreen-git** [comment]
Привет, GisGmp2_2 это библиотека(пакет) ее не нужно запускать как проект (класса Program.cs не должно быть, экспериментировал походу я).

Варианты использования:
1. Создать консольное приложение и подключить библиотеку через nuget 
2. В этом решении добавить консольное приложение(выбрать как запускаемый проект) и ссылку на проект GisGmp2_2 (сможешь редактировать эту библиотеку).

Пример (код можно взять так же из GisGmp2_2.Tests - покрытие кода тестами):

```csharp
using GisGmp.Charge;
using GisGmp.Common;
using GisGmp.Organization;
using GisGmp;
using System;
using GisGmp.Package;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            GisGmpBuilder gisgmp = new GisGmpBuilder()
            {
                SenderIdentifier = "3eacb7",
                SenderRole = "1"
            };

            var request = gisgmp.CreateImportChargesRequest(
                importedChargeTypes:
                new ImportedChargeType[]
                {
                    new ImportedChargeType(
                        id: "I_54a59db2-3845-4915-8770-dd95394aadb4",
                        supplierBillID: "32116102414550976332",
                        billDate: new DateTime(day: 30, month: 09, year: 2020, hour: 14, minute: 06, second: 30, millisecond: 313, kind: DateTimeKind.Local),
                        totalAmount: 500000,
                        purpose: "Плата за предоставление сведений из Единого государственного реестра недвижимости",
                        kbk: "32111301031016000130",
                        oktmo: "45348000",
                        payee: new Payee()
                        {
                            Name = "ФГБУ «ФКП Росреестра» по г Москва",
                            Inn = "7705401341",
                            Kpp = "770542151",
                            Ogrn = "7723819340452",
                            OrgAccount = new OrgAccount(
                                bank: new BankType(
                                    name: "ОПЕРАЦИОННЫЙ ДЕПАРТАМЕНТ БАНКА РОССИИ//Межрегиональное операционное управление Федерального казначейства г. Москва",
                                    bik: "024501901",
                                    correspondentBankAccount: "40102810045370000002"
                                    ),
                                accountNumber: "03100643000000019500"
                                )
                        },
                        payer: new ChargePayer(
                            payerIdentifier: "1220000000007712579832",
                            payerName: "Тестовый плательщик"
                            ),
                        budgetIndex: new BudgetIndexType(
                            status: Status.Item01,
                            paytReason: PaytReason.Item0,
                            taxPeriod: "0",
                            taxDocNumber: "0",
                            taxDocDate: "0"
                            )
                        )
                    {
                        OriginatorId = "3eb5fa",
                    }
                });

            Console.WriteLine(GisGmpBuilder.SerializerObject(request).InnerXml);
        }
    }
}

```

Библиотека создает "объекты запросов" для дальнейшей сериализации в xml и вставки в СМЭВ запрос.

Два типа методов:
1. gisgmp.CreateImportChargesRequest - возвращают объект запроса
2. gisgmp.ImportCharges - после генерации xml вызывают callback метод в который передают xml запроса (это для уменьшения кода). Но в этом случае необходимо передать callback метод в GisGmpBuilder  (CallBackReadyRequest = new CallBackData(NameMethod) )

P.S. Сейчас версия ГИС ГМП 2.4

**Comment by Grayzone90** [comment]
Спс) Будем разбираться

**Comment by Grayzone90** [comment]
Можно ещё вопрос, 
по идее гис гмп апи это soap, а чтобы сделать soap запрос нужен wsdl файл определений, на основе которого уже и генериться это soap поверх xml запрос, который отправляется в СМЭВ. Или есть ещё какие то подходы.
( эти wsdl файлы получают при оформление заявки или они есть где то в открытом доступе )

**Comment by MrGreen-git** [comment]
_Грубо накидаю информацию т.к. долго объяснять._

ГИС ГМП документы [ссылка](https://roskazna.gov.ru/gis/gosudarstvennaya-informacionnaya-sistema-o-gosudarstvennykh-i-municipalnykh-platezhakh-gis-gmp/dorozhnaya-karta-formaty-gis-gmp-2-4/?clear_cache=Y)
СМЭВ портал [ссылка](https://smev.gosuslugi.ru/portal/)
по этим ссылкам можно найти всю информацию (придется много читать/доступ получать - это самое сложное)

ГИС ГМП - сервис предоставляющий/обрабатывающий данные (поставщик), а ваше приложение потребитель.
СМЭВ - транспорт, пересылает xml между потребителем и поставщиком с помощью SOAP.

Примерная схема работы:
1. Вы работаете с сервисом СМЭВ (soap, wsdl)
2. Отправка в ГИС ГМП: Request(xml) -> SmevMessage(xml)->SOAP -> SMEV(service)
3. SMEV добавляет SmevMessage в очередь для ГИС ГМП.
4. ГИС ГМП запрашивает данные из СМЭВ: SOAP->SmevMessage->request
5. Ответ аналогично в обратном порядке

т.е. СМЭВ "унифицированный транспорт" для всех сервисов (к ГИС ГМП напрямую нельзя обратиться - нет интерфейса).
Маршрутизация между сервисами  - настройка SmevMessage
Маршрутизация между видами сведений (requests) в сервисе - корневой тег xml-request.

P.S. сервис в тех. реализации только СМЭВ, остальное сервис - как "предметная область."

**Comment by Grayzone90** [comment]
Прямо напишу,
Вот эта библиотека формирует запросы не используя wsdl, а в ручную генерит soap на основе шаблонов ( если я правильно понел ), т.е. wsdl не обязателен или как мне их вшивать в решение. Или мне не нужен, wsdl а клиентом-wsdl является СМЭВ который отправляет запрос на сервер
Я про то, как формировать soap на основе wsdl или шаблонов ( например как в либе )

**Comment by MrGreen-git** [comment]
Все правильно, только сервис здесь это СМЭВ3 и у него есть wsdl, вызываете метод SendRequest и как параметр передаете в него xml из этой библиотеки.

**Comment by Grayzone90** [comment]
А где в этой библиотеке файл определений, он же по идее нужен

**Comment by Grayzone90** [comment]
Вот смотрите на https://roskazna.gov.ru/gis/gosudarstvennaya-informacionnaya-sistema-o-gosudarstvennykh-i-municipalnykh-platezhakh-gis-gmp/ я взял пример запроса
![Screenshot_1](https://user-images.githubusercontent.com/39431529/127158806-e1c99699-40ad-4844-aaeb-13ad0b0a4d5a.png)
![Screenshot_2](https://user-images.githubusercontent.com/39431529/127158814-2169d9a8-a895-437f-80af-cccc8609a2ee.png)
![Screenshot_3](https://user-images.githubusercontent.com/39431529/127158821-cc84aec5-c990-4c12-9f07-2bd2b141af5a.png)
Как мне надо ручками строку этого запроса передавать через request или у меня есть wsdl файл,
на основе которого soapClient сформирует примерно подобный запрос и по http его пульнёт ?

**Comment by MrGreen-git** [comment]
Есть 2 варианта взаимодействия с ГИС ГМП:
1. Форматы взаимодействия версия 1.16.10 (СМЭВ2) wsdl в конце документации
2. Форматы взаимодействия версия 2.4 (СМЭВ3) 
Эта библиотека для СМЭВ3.
С 1 вариантом давно не работаю(думал что уже СМЭВ2 не поддерживается), этот вариант позволяет работать "напрямую с ГИС ГМП".

**Comment by Grayzone90** [comment]
Можно последний вопрос, я просто пытаюсь одно и тоже узнать в разных формулировках, но вы почему-то не отвечаете =)
1. Эта библиотека формирует что то подобное как на слайдах ? если да, то 2 вопрос
2. Эта либа формируют xml запрос наподоби выше приведённых слайдов на основе шаблонов так ??? ( ГЛАВНОЕ что мне интересно ) Почему НЕ используются вот эти wsdl файлы ??? а шаблоны ??? для формирования запроса строки запроса ( те как на слайде, как я понел ) ???

**Comment by MrGreen-git** [comment]
Минуту сейчас попытаюсь по другому объяснить. Это не SOAP.

**Comment by Grayzone90** [comment]
Последний вопрос из последних =)
А эта либа работает со CМЭВ3 ? текущей версий гмп 2.4 ? А я вот могу на тестовой среде смэв потестить что нибудь прям сейчас ? или что мне надо для теста, нужна ЭП для теста в тестовой среде

**Comment by MrGreen-git** [comment]
Работает под СМЭВ3 (для теста можно взять и эталонные сообщения в каждом виде сведений есть). ЭП и разобраться как подписывать. Также для тестовой среды нужно найти адрес сервиса на портале СМЭВ3 там будет и wsdl.
Со СМЭВ напрямую не работал, только через шину ХМАО (некоторые вещи автоматизированы). Нужно подписывать 2 ЭП - 1 ЭП сотрудника содержимое xml то, что формирует библиотека, 2 ЭП  органа власти весь SOAP. С подписанием нужно разбираться (сейчас ГИС ГМП принимает без подписи сотрудника), остается только подписать весь SOAP.

**Comment by Grayzone90** [comment]
Привет, крайне не удобно, но у вас нету случайно примера запроса, какой он должен быть в итоге в ГИС ГМП ( допустим там о начислении за что нибудь по какому нибудь ЛС ), через СМЭВ3, чтобы этот запрос через форму валидации запросов прошёл по ссылке https://smev3.gosuslugi.ru/portal/checkxmlform.jsp. 
Я нигде не нашёл цельного примера таких запросов, 
Есть схемы, есть wsdl, файлы, а как их вшивать в запрос к СМЭВ нигде нету, есть абстрактные описания, основанные на типе сведений которые нужны в конкретном кейсе, есть описания типов, а цельного примера, чтобы работала всё равно
нету
Чтобы было с чего начать
Вот ваша библиотека она же что то генерит, вот просто увидеть пример этой генерации, только именно через СМЭВ3

**Comment by MrGreen-git** [comment]
SOAP сообщения для СМЭВ3 нет.  Запросы можно отправлять еще через адаптер (https://smev3.gosuslugi.ru/portal/) вставляя данные для сервиса к примеру для ГИС ГМП и вроде как можно просмотреть полное SOAP сообщение.

**Comment by Grayzone90** [comment]
Да хорошо было бы увидеть 
Вот я нашёл валидные запросы, которые через форму проходят. Вот пример : 

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.2" xmlns:ns1="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.2" xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns:SendRequestRequest xmlns:ns="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.2" xmlns:basic="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.2"><ns:SenderProvidedRequestData Id="SIGNED_BY_CONSUMER" xmlns:ns1="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/basic/1.2" xmlns:ns="urn://x-artefacts-smev-gov-ru/services/message-exchange/types/1.2" ><ns:MessageID>7e14cef6-379c-11ea-9777-aaaaaa2ca900</ns:MessageID><ns:ReferenceMessageID>7e14cef6-379c-11ea-9777-aaaaaa2ca900</ns:ReferenceMessageID><ns:TransactionCode>7e17b4af-379c-11ea-aefa-001a4a1660a5|10000000000000000000|ByXTyP7c6gpiMt7zHtOYYnhHzB8QlNMe0J74yZYAIPA3Qnt3HwqsRl7WjzQUOtrsYXBqFvr69as8M4oX2V+CXneynwA5qvgF3nXrQW8dbmpQZzIkRpOcuKXJpIOjcSvLQxQ7EcLpQ7RnIcG+aQfG6rA7ns1v9YTVi2wGyVYtOgIYy3reaRgRHyRr05RdXsRHGNj+xCPNSJG80NCA1UJDRNrnM9Qj0/WcWQW4AqTQDiBkBdpvmT58jNmVK8hbaGBYnfv5e0SS1bR3guonpQvf04VEQccu0YvezVJsBSvQZ1oxXTmbcLzzCi5Kjt0xSwq/EEFBGyrokFoCcwnEQeBRZQ==</ns:TransactionCode><ns1:MessagePrimaryContent><ns1:DataRequest xmlns:ns1="urn://qa/8.0.0"><ns1:Request>RequestData</ns1:Request></ns1:DataRequest></ns1:MessagePrimaryContent><ns1:RefAttachmentHeaderList><ns1:RefAttachmentHeader><ns1:uuid>7d1d4f95-379c-11ea-9777-aaaaaa2ca900</ns1:uuid><ns1:Hash>DVKgZu/U7L2y1DRNQE70oIw2egkuEH4Q3MDJz9pXg+Q=</ns1:Hash><ns1:MimeType>image/jpeg</ns1:MimeType><ns1:SignaturePKCS7>MIIKvQYJKoZIhvcNAQcCoIIKrjCCCqoCAQExDjAMBggqhQMHAQECAgUAMAsGCSqGSIb3DQEHAaCCCDQwgggwMIIH3aADAgECAhAoNLeZtWjViekR3uUnrkTVMAoGCCqFAwcBAQMCMIIBZDEXMBUGCSqGSIb3DQEJARYIY2FAcnQucnUxGDAWBgUqhQNkARINMTAyNzcwMDE5ODc2NzEaMBgGCCqFAwOBAwEBEgwwMDc3MDcwNDkzODgxCzAJBgNVBAYTAlJVMSkwJwYDVQQIDCA3OCDQodCw0L3QutGCLdCf0LXRgtC10YDQsdGD0YDQszEqMCgGA1UEBwwh0LMuINCh0LDQvdC60YIt0J/QtdGC0LXRgNCx0YPRgNCzMS0wKwYDVQQJDCTRg9C7LiDQlNC+0YHRgtC+0LXQstGB0LrQvtCz0L4g0LQuMTUxMDAuBgNVBAsMJ9Cj0LTQvtGB0YLQvtCy0LXRgNGP0Y7RidC40Lkg0YbQtdC90YLRgDEmMCQGA1UECgwd0J/QkNCeICLQoNC+0YHRgtC10LvQtdC60L7QvCIxJjAkBgNVBAMMHdCf0JDQniAi0KDQvtGB0YLQtdC70LXQutC+0LwiMB4XDTE5MTAwMzEyNTgwNVoXDTIwMTAwMzEzMDgwNVowggFZMSwwKgYJKoZIhvcNAQkCDB3QotCV0KHQol/QmNChX9Cg0J7QmNCSX9Ch0JDQnTEaMBgGCCqFAwOBAwEBEgwwMDUwNDcwNTM5MjAxGDAWBgUqhQNkARINMTAzNTAwOTU2NzQ1MDEfMB0GA1UECgwW0JDQniDCq9Cg0KIg0JvQsNCx0YHCuzE7MDkGA1UECQwy0YPQuy4g0J/RgNC+0LvQtdGC0LDRgNGB0LrQsNGPLCDQtC4gMjMsINC60L7QvCAxMDExEzARBgNVBAcMCtCl0LjQvNC60LgxLzAtBgNVBAgMJjUwINCc0L7RgdC60L7QstGB0LrQsNGPINC+0LHQu9Cw0YHRgtGMMQswCQYDVQQGEwJSVTFCMEAGA1UEAww50JDQutGG0LjQvtC90LXRgNC90L7QtSDQvtCx0YnQtdGB0YLQstC+IMKr0KDQoiDQm9Cw0LHRgcK7MGYwHwYIKoUDBwEBAQEwEwYHKoUDAgIkAAYIKoUDBwEBAgIDQwAEQGOgzok7HgfjdSmigWiT7erFuoN7USHqdIWY4fdNUFCvk9vkyrXcHivG8tCJk0xsygGLMwC/Gzbr/Fv9au7SLOujggRpMIIEZTAOBgNVHQ8BAf8EBAMCBPAwHQYDVR0OBBYEFFjkwu13LNZ4nsNMUq9Jb+/K0zpVMIIBXwYDVR0jBIIBVjCCAVKAFP6ftCij337qOHL74JhmvqtBHuSsoYIBLKSCASgwggEkMR4wHAYJKoZIhvcNAQkBFg9kaXRAbWluc3Z5YXoucnUxCzAJBgNVBAYTAlJVMRgwFgYDVQQIDA83NyDQnNC+0YHQutCy0LAxGTAXBgNVBAcMENCzLiDQnNC+0YHQutCy0LAxLjAsBgNVBAkMJdGD0LvQuNGG0LAg0KLQstC10YDRgdC60LDRjywg0LTQvtC8IDcxLDAqBgNVBAoMI9Cc0LjQvdC60L7QvNGB0LLRj9C30Ywg0KDQvtGB0YHQuNC4MRgwFgYFKoUDZAESDTEwNDc3MDIwMjY3MDExGjAYBggqhQMDgQMBARIMMDA3NzEwNDc0Mzc1MSwwKgYDVQQDDCPQnNC40L3QutC+0LzRgdCy0Y/Qt9GMINCg0L7RgdGB0LjQuIIKTvdZNwAAAAAApDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwHQYDVR0gBBYwFDAIBgYqhQNkcQEwCAYGKoUDZHECMIIBMAYFKoUDZHAEggElMIIBIQwrItCa0YDQuNC/0YLQvtCf0YDQviBDU1AiICjQstC10YDRgdC40Y8gNC4wKQwsItCa0YDQuNC/0YLQvtCf0YDQviDQo9CmIiAo0LLQtdGA0YHQuNC4IDIuMCkMYdCh0LXRgNGC0LjRhNC40LrQsNGC0Ysg0YHQvtC+0YLQstC10YLRgdGC0LLQuNGPINCk0KHQkSDQoNC+0YHRgdC40Lgg0KHQpC8xMjQtMzM4MCDQvtGCIDExLjA1LjIwMTgMYdCh0LXRgNGC0LjRhNC40LrQsNGC0Ysg0YHQvtC+0YLQstC10YLRgdGC0LLQuNGPINCk0KHQkSDQoNC+0YHRgdC40Lgg0KHQpC8xMjgtMjk4MyDQvtGCIDE4LjExLjIwMTYwNgYFKoUDZG8ELQwrItCa0YDQuNC/0YLQvtCf0YDQviBDU1AiICjQstC10YDRgdC40Y8gNC4wKTBzBgNVHR8EbDBqMDSgMqAwhi5odHRwOi8vY2VydGVucm9sbC5jYS5ydC5ydS9jYV9ydGtfZ29zdDIwMTIuY3JsMDKgMKAuhixodHRwOi8vY29tcGFueS5ydC5ydS9jZHAvY2FfcnRrX2dvc3QyMDEyLmNybDCBhAYIKwYBBQUHAQEEeDB2MDoGCCsGAQUFBzAChi5odHRwOi8vY2VydGVucm9sbC5jYS5ydC5ydS9jYV9ydGtfZ29zdDIwMTIuY3J0MDgGCCsGAQUFBzAChixodHRwOi8vY29tcGFueS5ydC5ydS9jZHAvY2FfcnRrX2dvc3QyMDEyLmNydDArBgNVHRAEJDAigA8yMDE5MTAwMzEyNTgwNFqBDzIwMjAxMDAzMTI1ODA0WjAKBggqhQMHAQEDAgNBAMzWDgo/uFiY/gFkz0WSADZjKCOtF9FRRgLW8V2uTDvn1QKKGwb3v9tCgOtTCTx8p4FqYW5dCnWOFfAoqrYuOXExggJOMIICSgIBATCCAXowggFkMRcwFQYJKoZIhvcNAQkBFghjYUBydC5ydTEYMBYGBSqFA2QBEg0xMDI3NzAwMTk4NzY3MRowGAYIKoUDA4EDAQESDDAwNzcwNzA0OTM4ODELMAkGA1UEBhMCUlUxKTAnBgNVBAgMIDc4INCh0LDQvdC60YIt0J/QtdGC0LXRgNCx0YPRgNCzMSowKAYDVQQHDCHQsy4g0KHQsNC90LrRgi3Qn9C10YLQtdGA0LHRg9GA0LMxLTArBgNVBAkMJNGD0LsuINCU0L7RgdGC0L7QtdCy0YHQutC+0LPQviDQtC4xNTEwMC4GA1UECwwn0KPQtNC+0YHRgtC+0LLQtdGA0Y/RjtGJ0LjQuSDRhtC10L3RgtGAMSYwJAYDVQQKDB3Qn9CQ0J4gItCg0L7RgdGC0LXQu9C10LrQvtC8IjEmMCQGA1UEAwwd0J/QkNCeICLQoNC+0YHRgtC10LvQtdC60L7QvCICECg0t5m1aNWJ6RHe5SeuRNUwDAYIKoUDBwEBAgIFAKBpMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIwMDExNTEzMzk0NVowLwYJKoZIhvcNAQkEMSIEIA1SoGbv1Oy9stQ0TUBO9KCMNnoJLhB+ENzAyc/aV4PkMAwGCCqFAwcBAQMCBQAEQE41k5Kg/VzY5HcZ/xFab1HYh9ovzqvhknPLkxdmaINgpbh9TAJ7cHIR0szuZgvVKIMDO5yxbR7kQhHgi1wUnx4=</ns1:SignaturePKCS7></ns1:RefAttachmentHeader></ns1:RefAttachmentHeaderList></ns:SenderProvidedRequestData><ns:CallerInformationSystemSignature><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102012-gostr34112012-256"/><ds:Reference URI="#SIGNED_BY_CONSUMER"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:Transform Algorithm="urn://smev-gov-ru/xmldsig/transform"/></ds:Transforms><ds:DigestMethod Algorithm="urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34112012-256"/><ds:DigestValue>LbdyY28+hnthaVWZCdyRsV9ljZSRf5lKL0uqrdAnXfs=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>36JG8E3qG4xOZCIiuAuQMnTWtewF8aL858TK/2kncWzYWubSGZoucFjvVpCdBZW1F3WTxo5XgkdTcvn5T+29hg==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIIMDCCB92gAwIBAgIQKDS3mbVo1YnpEd7lJ65E1TAKBggqhQMHAQEDAjCCAWQxFzAVBgkqhkiG9w0BCQEWCGNhQHJ0LnJ1MRgwFgYFKoUDZAESDTEwMjc3MDAxOTg3NjcxGjAYBggqhQMDgQMBARIMMDA3NzA3MDQ5Mzg4MQswCQYDVQQGEwJSVTEpMCcGA1UECAwgNzgg0KHQsNC90LrRgi3Qn9C10YLQtdGA0LHRg9GA0LMxKjAoBgNVBAcMIdCzLiDQodCw0L3QutGCLdCf0LXRgtC10YDQsdGD0YDQszEtMCsGA1UECQwk0YPQuy4g0JTQvtGB0YLQvtC10LLRgdC60L7Qs9C+INC0LjE1MTAwLgYDVQQLDCfQo9C00L7RgdGC0L7QstC10YDRj9GO0YnQuNC5INGG0LXQvdGC0YAxJjAkBgNVBAoMHdCf0JDQniAi0KDQvtGB0YLQtdC70LXQutC+0LwiMSYwJAYDVQQDDB3Qn9CQ0J4gItCg0L7RgdGC0LXQu9C10LrQvtC8IjAeFw0xOTEwMDMxMjU4MDVaFw0yMDEwMDMxMzA4MDVaMIIBWTEsMCoGCSqGSIb3DQEJAgwd0KLQldCh0KJf0JjQoV/QoNCe0JjQkl/QodCQ0J0xGjAYBggqhQMDgQMBARIMMDA1MDQ3MDUzOTIwMRgwFgYFKoUDZAESDTEwMzUwMDk1Njc0NTAxHzAdBgNVBAoMFtCQ0J4gwqvQoNCiINCb0LDQsdGBwrsxOzA5BgNVBAkMMtGD0LsuINCf0YDQvtC70LXRgtCw0YDRgdC60LDRjywg0LQuIDIzLCDQutC+0LwgMTAxMRMwEQYDVQQHDArQpdC40LzQutC4MS8wLQYDVQQIDCY1MCDQnNC+0YHQutC+0LLRgdC60LDRjyDQvtCx0LvQsNGB0YLRjDELMAkGA1UEBhMCUlUxQjBABgNVBAMMOdCQ0LrRhtC40L7QvdC10YDQvdC+0LUg0L7QsdGJ0LXRgdGC0LLQviDCq9Cg0KIg0JvQsNCx0YHCuzBmMB8GCCqFAwcBAQEBMBMGByqFAwICJAAGCCqFAwcBAQICA0MABEBjoM6JOx4H43UpooFok+3qxbqDe1Eh6nSFmOH3TVBQr5Pb5Mq13B4rxvLQiZNMbMoBizMAvxs26/xb/Wru0izro4IEaTCCBGUwDgYDVR0PAQH/BAQDAgTwMB0GA1UdDgQWBBRY5MLtdyzWeJ7DTFKvSW/vytM6VTCCAV8GA1UdIwSCAVYwggFSgBT+n7Qoo99+6jhy++CYZr6rQR7krKGCASykggEoMIIBJDEeMBwGCSqGSIb3DQEJARYPZGl0QG1pbnN2eWF6LnJ1MQswCQYDVQQGEwJSVTEYMBYGA1UECAwPNzcg0JzQvtGB0LrQstCwMRkwFwYDVQQHDBDQsy4g0JzQvtGB0LrQstCwMS4wLAYDVQQJDCXRg9C70LjRhtCwINCi0LLQtdGA0YHQutCw0Y8sINC00L7QvCA3MSwwKgYDVQQKDCPQnNC40L3QutC+0LzRgdCy0Y/Qt9GMINCg0L7RgdGB0LjQuDEYMBYGBSqFA2QBEg0xMDQ3NzAyMDI2NzAxMRowGAYIKoUDA4EDAQESDDAwNzcxMDQ3NDM3NTEsMCoGA1UEAwwj0JzQuNC90LrQvtC80YHQstGP0LfRjCDQoNC+0YHRgdC40LiCCk73WTcAAAAAAKQwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMB0GA1UdIAQWMBQwCAYGKoUDZHEBMAgGBiqFA2RxAjCCATAGBSqFA2RwBIIBJTCCASEMKyLQmtGA0LjQv9GC0L7Qn9GA0L4gQ1NQIiAo0LLQtdGA0YHQuNGPIDQuMCkMLCLQmtGA0LjQv9GC0L7Qn9GA0L4g0KPQpiIgKNCy0LXRgNGB0LjQuCAyLjApDGHQodC10YDRgtC40YTQuNC60LDRgtGLINGB0L7QvtGC0LLQtdGC0YHRgtCy0LjRjyDQpNCh0JEg0KDQvtGB0YHQuNC4INCh0KQvMTI0LTMzODAg0L7RgiAxMS4wNS4yMDE4DGHQodC10YDRgtC40YTQuNC60LDRgtGLINGB0L7QvtGC0LLQtdGC0YHRgtCy0LjRjyDQpNCh0JEg0KDQvtGB0YHQuNC4INCh0KQvMTI4LTI5ODMg0L7RgiAxOC4xMS4yMDE2MDYGBSqFA2RvBC0MKyLQmtGA0LjQv9GC0L7Qn9GA0L4gQ1NQIiAo0LLQtdGA0YHQuNGPIDQuMCkwcwYDVR0fBGwwajA0oDKgMIYuaHR0cDovL2NlcnRlbnJvbGwuY2EucnQucnUvY2FfcnRrX2dvc3QyMDEyLmNybDAyoDCgLoYsaHR0cDovL2NvbXBhbnkucnQucnUvY2RwL2NhX3J0a19nb3N0MjAxMi5jcmwwgYQGCCsGAQUFBwEBBHgwdjA6BggrBgEFBQcwAoYuaHR0cDovL2NlcnRlbnJvbGwuY2EucnQucnUvY2FfcnRrX2dvc3QyMDEyLmNydDA4BggrBgEFBQcwAoYsaHR0cDovL2NvbXBhbnkucnQucnUvY2RwL2NhX3J0a19nb3N0MjAxMi5jcnQwKwYDVR0QBCQwIoAPMjAxOTEwMDMxMjU4MDRagQ8yMDIwMTAwMzEyNTgwNFowCgYIKoUDBwEBAwIDQQDM1g4KP7hYmP4BZM9FkgA2YygjrRfRUUYC1vFdrkw759UCihsG97/bQoDrUwk8fKeBamFuXQp1jhXwKKq2Ljlx</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature></ns:CallerInformationSystemSignature></ns:SendRequestRequest></soapenv:Body></soapenv:Envelope>

Осталось только узнать как в это сообщения для СМЭВ вшить сообщение для ГИС ГМП

**Comment by MrGreen-git** [comment]
Вот еще есть репозиторий по СМЭВ 3 https://github.com/burcevsemyon/Smev3Sharp
